spring.application.name=consultorio-ms-medico
server.port=8884
#
## Configurando o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/db-medico
spring.datasource.username=medico
spring.datasource.password=123456
#
## Configurando JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect