spring.application.name=consultorio-ms-medico
server.port=8080
#
## Configurando o Banco de Dados
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
#
## Configurando JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update