apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-medico
spec:
  serviceName: "service-medico"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5434
          env:
            - name: POSTGRES_DB
              value: "db-medico"
            - name: POSTGRES_USER
              value: "medico"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-medico
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: medico-pvc